[package]
name = "basic_http"
version = "0.1.0"
authors = ["Vadym Maslov <mrvadamas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
# mongodb = "0.4.0"